version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: netflix_postgres
    restart: always
    environment:
      POSTGRES_DB: netflix_db
      POSTGRES_USER: netflix_user
      POSTGRES_PASSWORD: netflix_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netflix_network

  backend:
    build: .
    container_name: netflix_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/netflix_db
      SPRING_DATASOURCE_USERNAME: netflix_user
      SPRING_DATASOURCE_PASSWORD: netflix_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - netflix_network

volumes:
  postgres_data:

networks:
  netflix_network:
